# FROM node:lts-alpine3.22 AS base

# WORKDIR /src

# ENV NODE_ENV=development
# ENV PORT=5000

# COPY package.json package-lock.json* ./

# RUN npm install

# COPY  . .

# EXPOSE 5000

# CMD ["npm", "run", "dev"]



FROM node:lts-alpine3.22 AS production

WORKDIR /src

ENV NODE_ENV=production
ENV PORT=5000

COPY package.json package-lock.json* ./

RUN npm ci 

COPY . .

EXPOSE 5000

CMD ["node", "server.js"]